"""Enumerations shared across the OmniRAG domain model.

These values are persisted inside vector-store payloads, therefore their string
values are part of the on-disk contract: rename with care.
"""

from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    """`str`-backed enum so values serialise transparently to JSON/payloads."""

    def __str__(self) -> str:  # pragma: no cover - trivial
        return str(self.value)


class FileType(StrEnum):
    """Supported (and planned) input container formats."""

    PDF = "pdf"
    DOCX = "docx"
    PPTX = "pptx"
    TXT = "txt"
    MARKDOWN = "md"
    IMAGE = "image"
    # Planned - the router already knows the names so adding a processor is a
    # one-file change (see omnirag/ingestion/router.py).
    XLSX = "xlsx"
    HTML = "html"
    UNKNOWN = "unknown"


class BlockType(StrEnum):
    """Semantic type of a :class:`~omnirag.core.models.ContentBlock`."""

    TEXT = "text"
    HEADING = "heading"
    OCR_TEXT = "ocr_text"
    HANDWRITING = "handwriting"
    IMAGE = "image"
    TABLE = "table"
    CHART = "chart"
    DIAGRAM = "diagram"
    CAPTION = "caption"
    SPEAKER_NOTES = "speaker_notes"
    PAGE_SNAPSHOT = "page_snapshot"

    @property
    def is_visual(self) -> bool:
        """True when the block carries an original visual worth sending to a VLM."""
        return self in _VISUAL_BLOCKS

    @property
    def is_textual(self) -> bool:
        return self in _TEXTUAL_BLOCKS


_VISUAL_BLOCKS = frozenset(
    {
        BlockType.IMAGE,
        BlockType.CHART,
        BlockType.DIAGRAM,
        BlockType.HANDWRITING,
        BlockType.PAGE_SNAPSHOT,
    }
)

_TEXTUAL_BLOCKS = frozenset(
    {
        BlockType.TEXT,
        BlockType.HEADING,
        BlockType.OCR_TEXT,
        BlockType.CAPTION,
        BlockType.SPEAKER_NOTES,
        BlockType.TABLE,
    }
)


class SourceKind(StrEnum):
    """How the text of a block was obtained. Drives trust/confidence display."""

    DIGITAL = "digital"          # selectable text extracted losslessly
    OCR = "ocr"                  # optical character recognition
    VISION = "vision"            # generated by a vision model (description)
    STRUCTURED = "structured"    # parsed structure, e.g. a DOCX/PPTX table
    DERIVED = "derived"          # normalised/summarised from another block


class IngestionStatus(StrEnum):
    """Lifecycle of a document inside a session."""

    PENDING = "pending"
    PARSING = "parsing"
    ANALYZING = "analyzing"
    CHUNKING = "chunking"
    EMBEDDING = "embedding"
    INDEXING = "indexing"
    READY = "ready"
    FAILED = "failed"
    DUPLICATE = "duplicate"


class PipelineStage(StrEnum):
    """User-facing progress stages surfaced by the UI."""

    UPLOADING = "Uploading"
    PARSING = "Parsing"
    EXTRACTING_TEXT = "Extracting text"
    ANALYZING_VISUALS = "Analyzing visuals"
    CHUNKING = "Generating chunks"
    EMBEDDING = "Creating embeddings"
    INDEXING = "Indexing"
    READY = "Ready"


class Language(StrEnum):
    """Coarse language buckets used for filtering and prompt steering."""

    ARABIC = "ar"
    ENGLISH = "en"
    MIXED = "mixed"
    UNKNOWN = "unknown"


class Role(StrEnum):
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class RetrievalStrategy(StrEnum):
    VECTOR = "vector"
    KEYWORD = "keyword"
    HYBRID = "hybrid"
