"""Table extraction and multi-representation serialisation.

A table is stored in several forms at once so that different question types can
be answered from it:

1. **structured** rows/columns — numeric relationships stay intact;
2. **Markdown** serialisation — what the LLM actually reads;
3. **semantic summary** — deterministic prose ("columns X, Y; 14 rows; numeric
   columns …") that makes the table findable by vector search, which would
   otherwise struggle with bare grids of numbers;
4. **visual crop reference** where the source is an image or PDF region.

The summary is generated by parsing, not by an LLM: it is cheaper, deterministic
and cannot hallucinate a value that is not in the table.
"""

from __future__ import annotations

import re
from typing import Any, List, Optional, Sequence

from omnirag.core.models import TableData
from omnirag.utils.logging import get_logger
from omnirag.utils.text import clean_text, truncate

logger = get_logger(__name__)

_NUMBER_RE = re.compile(r"^[\s\(\)\-+]*[\d٠-٩][\d٠-٩.,\s%٪]*\)?$")
_ARABIC_DIGITS = str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789")
MAX_SUMMARY_COLUMNS = 12
MAX_MARKDOWN_ROWS = 200


def build_table(
    rows: Sequence[Sequence[Any]],
    *,
    has_header: bool = True,
    caption: str = "",
) -> Optional[TableData]:
    """Normalise raw rows into a :class:`TableData`, or ``None`` if unusable."""
    cleaned = _clean_rows(rows)
    if not cleaned:
        return None
    if len(cleaned) < 2 and len(cleaned[0]) < 2:
        return None  # a single cell is not a table

    header_looks_real = has_header and _looks_like_header(cleaned[0])
    table = TableData.from_rows(cleaned, has_header=header_looks_real)
    if table.n_cols == 0:
        return None

    if len(table.rows) > MAX_MARKDOWN_ROWS:
        # Keep the structure complete but bound the serialisation we send to
        # the model; the full rows remain available in `table.rows`.
        from omnirag.core.models import _rows_to_markdown

        table.markdown = _rows_to_markdown(
            table.header, table.rows[:MAX_MARKDOWN_ROWS], table.n_cols
        ) + f"\n\n_({len(table.rows) - MAX_MARKDOWN_ROWS} further rows not shown)_"

    table.summary = summarize_table(table, caption=caption)
    return table


def _clean_rows(rows: Sequence[Sequence[Any]]) -> List[List[str]]:
    out: List[List[str]] = []
    for row in rows:
        if row is None:
            continue
        cells = [clean_text(str(cell)) if cell is not None else "" for cell in row]
        cells = [c.replace("\n", " ").strip() for c in cells]
        if any(cells):
            out.append(cells)
    return out


def _looks_like_header(row: Sequence[str]) -> bool:
    """A header row is mostly non-numeric, non-empty labels."""
    values = [c for c in row if c.strip()]
    if not values:
        return False
    numeric = sum(1 for c in values if is_numeric_cell(c))
    return numeric <= len(values) * 0.4


def is_numeric_cell(value: str) -> bool:
    text = value.strip().translate(_ARABIC_DIGITS)
    if not text:
        return False
    return bool(_NUMBER_RE.match(text))


def parse_number(value: str) -> Optional[float]:
    """Parse a cell into a float, tolerating thousands separators and (1,234)."""
    text = value.strip().translate(_ARABIC_DIGITS)
    if not text:
        return None
    negative = text.startswith("(") and text.endswith(")")
    text = text.strip("()").replace(",", "").replace("٪", "").replace("%", "").strip()
    if not text:
        return None
    try:
        number = float(text)
    except ValueError:
        return None
    return -number if negative else number


def summarize_table(table: TableData, *, caption: str = "") -> str:
    """Deterministic, hallucination-free description used for vector retrieval."""
    parts: List[str] = []
    if caption:
        parts.append(f"Table: {truncate(clean_text(caption), 160)}")

    header = table.header or []
    if header:
        shown = [h for h in header if h][:MAX_SUMMARY_COLUMNS]
        suffix = "" if len(header) <= MAX_SUMMARY_COLUMNS else f" (+{len(header) - MAX_SUMMARY_COLUMNS} more)"
        parts.append(f"Columns: {', '.join(shown)}{suffix}.")

    parts.append(f"{table.n_rows} data rows across {table.n_cols} columns.")

    # Row labels (first column) make "what does the row for X say" findable.
    if table.rows:
        labels = [row[0] for row in table.rows[:15] if row and row[0] and not is_numeric_cell(row[0])]
        if labels:
            parts.append(f"Row labels include: {', '.join(labels[:15])}.")

    numeric_columns = _numeric_column_ranges(table)
    if numeric_columns:
        parts.append("Numeric ranges: " + "; ".join(numeric_columns) + ".")

    return " ".join(parts)


def _numeric_column_ranges(table: TableData, limit: int = 6) -> List[str]:
    """``"Revenue: 1200 to 8400"`` for each numeric column (real values only)."""
    if not table.rows:
        return []
    out: List[str] = []
    for index in range(min(table.n_cols, 20)):
        values: List[float] = []
        for row in table.rows:
            if index >= len(row):
                continue
            number = parse_number(row[index])
            if number is not None:
                values.append(number)
        if len(values) < 2:
            continue
        name = (
            table.header[index]
            if table.header and index < len(table.header) and table.header[index]
            else f"column {index + 1}"
        )
        out.append(f"{name}: {_fmt(min(values))} to {_fmt(max(values))}")
        if len(out) >= limit:
            break
    return out


def _fmt(value: float) -> str:
    if value == int(value) and abs(value) < 1e15:
        return str(int(value))
    return f"{value:g}"


def table_to_text(table: TableData, *, caption: str = "") -> str:
    """Full retrieval text: summary first (dense, searchable), then the grid."""
    parts = []
    if caption:
        parts.append(clean_text(caption))
    if table.summary:
        parts.append(table.summary)
    if table.markdown:
        parts.append(table.markdown)
    return "\n\n".join(p for p in parts if p).strip()


__all__ = [
    "TableData",
    "build_table",
    "is_numeric_cell",
    "parse_number",
    "summarize_table",
    "table_to_text",
]
